sudo: required
services:
    - docker

before_install:
    - docker build -t kevinzhang99/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true kevinzhang99/docker-react npm run test -- --coverage

language: generic

